app:
    resource: "@AppBundle/Controller/"
    type:     annotation

os_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

home:
    path:     /index
    defaults: { _controller: AppBundle:Default:intro }

user_login:
    path:     /user/login
    defaults: { _controller: AppBundle:Security:login }

user_login_check:
    path:     /user/login/check
    defaults: { _controller: AppBundle:Security:check }

user_register:
    path:      /user/register
    defaults: { _controller: AppBundle:Registration:register }

user_logout:
    path:     /user/logout
    defaults: { _controller: AppBundle:Security:logout }
